### ISSUE TITLE
tutorials from README are missing in repository

### ISSUE THREAD

**Issue by hannesm** [janestreet/memtrace_viewer#1]
clicking on either of the three links in README in the tutorial section leads to a 404. They sound very interesting, it would be nice if they were added to this repository.

**Comment by lpw25** [comment]
Those exact tutorials aren't going to made available because they use internal programs for their examples, but @lukemaurer is working on a blog post announcing this viewer and containing essentially the same tutorial material. We'll update the readme to point to that once it is done (should be some time in the next two weeks).

**Comment by lpw25** [comment]
The blog post is [now up](https://blog.janestreet.com/finding-memory-leaks-with-memtrace/).

**Comment by hannesm** [comment]
thanks Leo.
