### ISSUE TITLE
Tutorial links and blog post

### ISSUE THREAD

**Issue by francoisthire** [janestreet/memtrace_viewer#3]
As mentioned in #1 , links in the readme file lead to a 404 error. If these tutorials are used internally, maybe it would be nice to add a line to say so, otherwise we think it is broken (if for technical reasons it is difficult to modify these lines).

Instead, the following (very nice and clear btw) blog post exists:

- https://blog.janestreet.com/finding-memory-leaks-with-memtrace/

Maybe adding the link in the README file could be helpful? I also noticed that the following link in the blog post is broken (404):

- https://blog.janestreet.com/finding-memory-leaks-with-memtrace/lifetimes_of_queued_objects.ml

**Comment by lpw25** [comment]
Sorry about this. This issue has been fixed weeks ago internally, but our public release process has been frozen due to a breaking change in Core that is taking a while to get through the release process.

I'm going to close this issue since it should get resolved automatically as soon as our release process gets unstuck.
